name: Scholar Bot
on:
  push:
    branches: [main]


  # This workflow can be executed inside another workfow file
  workflow_call:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write


jobs:
  scholar:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - id: pygscholar
      uses: ./add-publications
      with:
        name: "Henrik Finsberg"
        scholar_id: "NDPIHoEAAAAJ"
        cache_dir: ".pygscholar"
        working-directory: "."
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo title "$TITLE"
      shell: bash
      env:
        TITLE: ${{ steps.pygscholar.outputs.title }}
  