name: Open PR
on:
  push:
    branches: [main]

jobs:
  open_pr:

    permissions:
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create pull request
      run: gh pr create -B main -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
