name: Open PR
on:
  # This workflow can be executed inside another workfow file
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes 

permissions:
  pull-requests: write
  contents: write

jobs:
  push_branch:
    uses: ./.github/workflows/push_branch.yml
    
  open_pr:
    needs: [push_branch]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create pull request
      run: gh pr create -B main -H scholar-bot-update --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
