name: Push branch
on:
  push:
    branches: [main]

jobs:
  push_branch:

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # setup pytohn
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Create new file
      run: python3 main.py
    - name: Commit report
      run: |
        git config --global user.name 'SholarBot'
        git config --global user.email 'scholarbot@users.noreply.github.com'
        git checkout -b scholar-bot-update
        git add .
        git commit -m "Update report"
        git push origin scholar-bot-update
