name: Scholar Bot
on:
  push:
    branches:
      - main

jobs:
  scholar:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - id: pygscholar
      uses: finsberg/add-publications@main
      with:
        name: "Henrik Finsberg"
        scholar_id: "NDPIHoEAAAAJ"
        cache_dir: ".pygscholar"
        working-directory: "."
        token: ${{ secrets.GITHUB_TOKEN }}
        bibdir: "_publications"
    - run: echo title "$TITLE"
      shell: bash
      env:
        TITLE: ${{ steps.pygscholar.outputs.title }}
  